services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - nginx-proxy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  nginx-proxy-net:
    external: true
