
services:
  nginx:
    image: nginx:latest
    network_mode: host
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: on-failure
