server {
    listen 443 ssl;
    server_name perdomodoces.com.br www.perdomodoces.com.br;

    ssl_certificate /etc/nginx/certs/perdomodoces.com.br/wildcard.fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/perdomodoces.com.br/wildcard.key.pem;

    # Logs
    access_log /var/log/nginx/www.perdomodoces.access.log;
    error_log  /var/log/nginx/www.perdomodoces.error.log warn;

    # Admin do WordPress
    location /wordpress/wp-admin {
        proxy_pass http://127.0.0.1:9080/wp-admin;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Site do WordPress na rota base (via URL personalizada)
    location /uma-doce-historia-10-anos-perdomo {
        proxy_pass http://127.0.0.1:9080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Rota raiz ou outras
    location / {
        proxy_pass http://127.0.0.1:5000; # Seu outro serviço
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
